### PR TITLE
Use Codecov global uploader

### PR DESCRIPTION
**Pull request by stevepeak**
This tool (as of now) works better then the Python version, which I'll be upgrading soon.

Thank you :)

### CODE REVIEW

**Comment by stevepeak** [comment]
Bingo! https://codecov.io/gh/damianszczepanik/cucumber-reporting?ref=58f613d

**Comment by damianszczepanik** [comment]
Nice - good job :-)

**Comment by damianszczepanik** [comment]
ANy idea why this https://img.shields.io/codecov/c/github/damianszczepanik/cucumber-reporting/master.svg displays invalid data? This works for other site but not for mine

**Comment by stevepeak** [comment]
Odd... the repository duplicated again. I may have deleted the "wrong" one earlier. Fixed up now. Thanks!

**Comment by damianszczepanik** [comment]
Perfect!

**Comment by damianszczepanik** [comment]
@stevepeak 
I have similar problem with https://github.com/damianszczepanik/maven-cucumber-reporting and that might be because I have renamed the project. Can you take a look at this?
https://codecov.io/github/damianszczepanik/maven-cucumber-reporting

**Comment by stevepeak** [comment]
Hey @damianszczepanik I'm not seeing two double repos for `maven-cucumber-reporting`. Is this the correct repo? https://codecov.io/github/damianszczepanik/cucumber-reporting

**Comment by damianszczepanik** [comment]
From https://github.com/damianszczepanik/maven-cucumber-reporting
to https://codecov.io/github/damianszczepanik/maven-cucumber-reporting

**Pull request merged**
