### PR TITLE
Allow undefined and pending steps to not fail

### PR DESCRIPTION
**Pull request by damianszczepanik**
Issue #692

### CODE REVIEW

**Comment by damianszczepanik** [comment]
With this change user can configure which statuses won't fail scenario and later feature. As presented, even not all steps are passed, scenario remains passed.
skipped

**Comment by damianszczepanik** [comment]
This change introduces most wanted feature that allows to treat undefined/skipped steps as passed and thus not fail scenario. Please review and let me know if this is what you expect!

@a1dutch @SteveDonie @laxersaz @ransom4real @silviatejera @sbpk516 @mpkorstanje @imtiazhossain @plank87 @kth13 @svsforsuccess @maultosar @LucasSq @jess8147 @KLBonn @kalyankp @UltimateGeek @ptrthomas @iragoubi @aamol

**Comment by imtiazhossain** [comment]
Thanks!

**Comment by mpkorstanje** [comment]
In Cucumber this is called strict/no-strict. By default Cucumber run in no-strict mode. Perhaps rather then selecting which statuses are passed you can provide a single strict flag. That way the report andCucumberi use the same terminology.

**Comment by damianszczepanik** [comment]
I haven't use default mode I've been using strict. This is valuable comment and I will try to make it easy to use for everyone who know how strict mode works and for those who like to decide which statuses should fail scenario and which don't.

**Comment by iragoubi** [comment]
Thanks, when will this configuration be available on maven-cucumber-reports ?

**Comment by damianszczepanik** [comment]
The plan stays as: test,  write unit test, release this project and then upgrade Jenkins plugin and others.

**Comment by SteveDonie** [comment]
Excellent! Much excitement from me.

**Comment by a1dutch** [comment]
@damianszczepanik agree about the [strict](https://cucumber.io/docs/cucumber/api/#step-results) flag, this is standard cucumber flag and should be the default behaviour.

Just supporting the strict mode might be a simpler option, cucumber hasn't seen the need to add any additional configuration for what status's are failed.

**Comment by kasunalwis** [comment]
In which version we have this fixed. I trued with 0.9.5.RC1 but didnt work

**Comment by damianszczepanik** [comment]
There is no such version https://github.com/damianszczepanik/cucumber-reporting/releases

**Pull request merged**
