### PR TITLE
Disable or speed up "Tags" page

### PR DESCRIPTION
**Pull request by damianszczepanik**
Issue #925

### CODE REVIEW

**Comment by damianszczepanik** [comment]
@mattventura this change speeds up tags generation however I'm not sure if this is enough for you. Can you test this change? Or share JSON file so I can examine fix

**Comment by mattventura** [comment]
Yep, this speeds it up significantly if I exclude all the tags. Unfortunately I can't provide my test file due to company info, but it cut the time down significantly. Thank you!

**Comment by damianszczepanik** [comment]
Then is it good enough to make this change ready for release? If so I will update tests and merge it.

**Comment by mattventura** [comment]
The only thing I noticed is that the excluded tags still show up in the tags overview page, but they link to a nonexistent page. For usability, it might be nice to not have them be normal text rather than links if the tag was filtered out. Other than that, looks fine to me.

**Pull request merged**
