### PR TITLE
fixed NPE

### PR DESCRIPTION
**Pull request by dinatomsk**
NPE because Scenario.id is private final field and is always initialized as null
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/201%23issuecomment-145311290%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/201%23issuecomment-145322752%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/201%23issuecomment-145734000%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/201%23issuecomment-145909844%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/201%23issuecomment-145311290%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.80%25%60%5Cn%3E%20Merging%20%2A%2A%23201%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20decrease%20coverage%20by%20%2A%2A-0.09%25%2A%2A%20as%20of%20%5B%60dc40971%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%23201%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%20%20Files%20%20%20%20%20%20%20%20%20%20%2032%20%20%20%20%2032%20%20%20%20%20%20%20%5Cn%20%20Stmts%20%20%20%20%20%20%20%20%201148%20%20%201148%20%20%20%20%20%20%20%5Cn%20%20Branches%20%20%20%20%20%20%20161%20%20%20%20163%20%20%20%20%20%2B2%5Cn%20%20Methods%20%20%20%20%20%20%20%20%20%200%20%20%20%20%20%200%20%20%20%20%20%20%20%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn-%20Hit%20%20%20%20%20%20%20%20%20%20%201009%20%20%201008%20%20%20%20%20-1%5Cn-%20Partial%20%20%20%20%20%20%20%20%2043%20%20%20%20%2044%20%20%20%20%20%2B1%5Cn%20%20Missed%20%20%20%20%20%20%20%20%20%2096%20%20%20%20%2096%20%20%20%20%20%20%20%5Cn%60%60%60%5Cn%5Cn%3E%20Review%20entire%20%5BCoverage%20Diff%5D%5B4%5D%20as%20of%20%5B%60dc40971%60%5D%5B3%5D%5Cn%5Cn%5Cn%5B1%5D%3A%20https%3A//codecov.io/github/damianszczepanik/cucumber-reporting%3Fref%3Ddc40971a9c04ec3acfbea8545c83ff308313053c%5Cn%5B2%5D%3A%20https%3A//codecov.io/github/damianszczepanik/cucumber-reporting/features/suggestions%3Fref%3Ddc40971a9c04ec3acfbea8545c83ff308313053c%5Cn%5B3%5D%3A%20https%3A//codecov.io/github/damianszczepanik/cucumber-reporting/commit/dc40971a9c04ec3acfbea8545c83ff308313053c%5Cn%5B4%5D%3A%20https%3A//codecov.io/github/damianszczepanik/cucumber-reporting/compare/9a0104c3206d3c962dca6429a5e1628e1f8ccf5f...dc40971a9c04ec3acfbea8545c83ff308313053c%5Cn%5Cn%3E%20Powered%20by%20%5BCodecov%5D%28https%3A//codecov.io%29.%20Updated%20on%20successful%20CI%20builds.%22%2C%20%22created_at%22%3A%20%222015-10-04T02%3A36%3A18Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8655789%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/codecov-io%22%7D%7D%2C%20%7B%22body%22%3A%20%22Why%20your%20scenarios%20don%27t%20have%20ID%3F%22%2C%20%22created_at%22%3A%20%222015-10-04T06%3A43%3A40Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/9612911%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik%22%7D%7D%2C%20%7B%22body%22%3A%20%22Our%20feature%20files%20contain%20%27Background%27%20sections%20and%20in%20the%20resulting%20json%20file%20these%20sections%20are%20transferred%20into%20the%20scenarios%20without%20identifiers.%22%2C%20%22created_at%22%3A%20%222015-10-06T03%3A38%3A41Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1821499%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dinatomsk%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20also%20have%20steps%20that%20are%20executed%20as%20background%20and%20standard%20steps%20and%20no%20such%20problem%20to%20be%20honest...%22%2C%20%22created_at%22%3A%20%222015-10-06T16%3A00%3A22Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/9612911%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/damianszczepanik/cucumber-reporting/pull/201#issuecomment-145311290'>General Comment</a></b>
- <a href='https://github.com/codecov-io'></a> ## [Current coverage][1] is `87.80%`
> Merging **#201** into **master** will decrease coverage by **-0.09%** as of [`dc40971`][3]
```diff
@@            master   #201   diff @@
=====================================
Files           32     32
Stmts         1148   1148
Branches       161    163     +2
Methods          0      0
=====================================
- Hit           1009   1008     -1
- Partial         43     44     +1
Missed          96     96
```
> Review entire [Coverage Diff][4] as of [`dc40971`][3]
[1]: https://codecov.io/github/damianszczepanik/cucumber-reporting?ref=dc40971a9c04ec3acfbea8545c83ff308313053c
[2]: https://codecov.io/github/damianszczepanik/cucumber-reporting/features/suggestions?ref=dc40971a9c04ec3acfbea8545c83ff308313053c
[3]: https://codecov.io/github/damianszczepanik/cucumber-reporting/commit/dc40971a9c04ec3acfbea8545c83ff308313053c
[4]: https://codecov.io/github/damianszczepanik/cucumber-reporting/compare/9a0104c3206d3c962dca6429a5e1628e1f8ccf5f...dc40971a9c04ec3acfbea8545c83ff308313053c
> Powered by [Codecov](https://codecov.io). Updated on successful CI builds.
- <a href='https://github.com/damianszczepanik'></a> Why your scenarios don't have ID?
- <a href='https://github.com/dinatomsk'></a> Our feature files contain 'Background' sections and in the resulting json file these sections are transferred into the scenarios without identifiers.
- <a href='https://github.com/damianszczepanik'></a> I also have steps that are executed as background and standard steps and no such problem to be honest...

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/201?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/201?approve=1'></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/201'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by damianszczepanik** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/damianszczepanik/cucumber-reporting/pull/201'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by damianszczepanik** [comment]
Why your scenarios don't have ID?

**Comment by dinatomsk** [comment]
Our feature files contain 'Background' sections and in the resulting json file these sections are transferred into the scenarios without identifiers.

**Comment by damianszczepanik** [comment]
I also have steps that are executed as background and standard steps and no such problem to be honest...

**Pull request merged**
