### PR TITLE
Introducing DataTables to be able to search, filter and sort the overview tables

### PR DESCRIPTION
**Pull request by tmullender**
We had a request to be able to search, sort and filter the overview tables in the reports.  

[DataTables](https://datatables.net) is a plug-in for the jQuery Javascript library that lets add various functionality to tables so I've used it to add the functionality we were asked for as well as pagination.  

It looks like there is a parallel effort to use table sorter, but I'd already done this so I thought I'd submit it. Feel free to ignore this if you already have plans to do it a different way.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/208%23issuecomment-149910514%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/208%23issuecomment-149980933%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/208%23issuecomment-150024874%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/208%23issuecomment-150158525%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/208%23issuecomment-150315882%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/208%23issuecomment-150500644%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/208%23issuecomment-150525019%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/208%23issuecomment-150638060%22%2C%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/208%23issuecomment-151286957%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik/cucumber-reporting/pull/208%23issuecomment-149910514%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%23%23%20%5BCurrent%20coverage%5D%5B1%5D%20is%20%6087.56%25%60%5Cn%3E%20Merging%20%2A%2A%23208%2A%2A%20into%20%2A%2Amaster%2A%2A%20will%20not%20affect%20coverage%20as%20of%20%5B%605067e73%60%5D%5B3%5D%5Cn%5Cn%5Cn%60%60%60diff%5Cn%40%40%20%20%20%20%20%20%20%20%20%20%20%20master%20%20%20%20%23208%20%20%20diff%20%40%40%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%20%20Files%20%20%20%20%20%20%20%20%20%20%2032%20%20%20%20%20%2032%20%20%20%20%20%20%20%5Cn%20%20Stmts%20%20%20%20%20%20%20%20%201158%20%20%20%201158%20%20%20%20%20%20%20%5Cn%20%20Branches%20%20%20%20%20%20%20164%20%20%20%20%20164%20%20%20%20%20%20%20%5Cn%20%20Methods%20%20%20%20%20%20%20%20%20%200%20%20%20%20%20%20%200%20%20%20%20%20%20%20%5Cn%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%5Cn%20%20Hit%20%20%20%20%20%20%20%20%20%20%201014%20%20%20%201014%20%20%20%20%20%20%20%5Cn%20%20Partial%20%20%20%20%20%20%20%20%2045%20%20%20%20%20%2045%20%20%20%20%20%20%20%5Cn%20%20Missed%20%20%20%20%20%20%20%20%20%2099%20%20%20%20%20%2099%20%20%20%20%20%20%20%5Cn%60%60%60%5Cn%5Cn%3E%20Review%20entire%20%5BCoverage%20Diff%5D%5B4%5D%20as%20of%20%5B%605067e73%60%5D%5B3%5D%5Cn%5Cn%5Cn%5B1%5D%3A%20https%3A//codecov.io/github/damianszczepanik/cucumber-reporting%3Fref%3D5067e736c2e0efb9c80eaacff517891032744d00%5Cn%5B2%5D%3A%20https%3A//codecov.io/github/damianszczepanik/cucumber-reporting/features/suggestions%3Fref%3D5067e736c2e0efb9c80eaacff517891032744d00%5Cn%5B3%5D%3A%20https%3A//codecov.io/github/damianszczepanik/cucumber-reporting/commit/5067e736c2e0efb9c80eaacff517891032744d00%5Cn%5B4%5D%3A%20https%3A//codecov.io/github/damianszczepanik/cucumber-reporting/compare/4b1b8c6d1d1d56f77d4394c8270ac5345cbc8aee...5067e736c2e0efb9c80eaacff517891032744d00%5Cn%5Cn%3E%20Powered%20by%20%5BCodecov%5D%28https%3A//codecov.io%29.%20Updated%20on%20successful%20CI%20builds.%22%2C%20%22created_at%22%3A%20%222015-10-21T14%3A18%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/8655789%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/codecov-io%22%7D%7D%2C%20%7B%22body%22%3A%20%22Looks%20good%2C%20but%3A%5Cr%5Cn-%20can%20you%20merge%20all%20commits%20into%20one%20and%20then%20publish%20PR%3F%5Cr%5Cn-%20I%20would%20like%20to%20see%20screenshot%20with%20new%20table%2C%20please%20attach%20%22%2C%20%22created_at%22%3A%20%222015-10-21T18%3A09%3A31Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/9612911%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik%22%7D%7D%2C%20%7B%22body%22%3A%20%22%21%5Bstepstatistics%5D%28https%3A//cloud.githubusercontent.com/assets/4955781/10650145/bd0996d6-783f-11e5-88f9-9d27976d288b.png%29%5Cr%5Cn%5Cr%5Cn%21%5Bfeaturestatistics%5D%28https%3A//cloud.githubusercontent.com/assets/4955781/10650079/751dc806-783f-11e5-9c93-effa55bde6c1.png%29%5Cr%5Cn%5Cr%5CnI%20can%27t%20share%20the%20features%20I%20was%20testing%20with%20due%20to%20company%20policy%20so%20I%27ve%20generated%20reports%20for%20cucumber-jvm%27s%20%5Bjava-helloworld%5D%28https%3A//github.com/cucumber/cucumber-jvm/tree/master/examples/java-helloworld%29%20example.%20%20If%20you%20have%20a%20more%20complex%20example%20you%20want%20to%20see%20then%20let%20me%20know%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-10-21T21%3A08%3A57Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4955781%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tmullender%22%7D%7D%2C%20%7B%22body%22%3A%20%22Nice%20feature%21%20%5Cr%5CnWhat%20I%20don%27t%20like%20that%20search%20input%20is%20not%20aligned%20with%20table%20on%20tag%20overview%20and%20feature%20overview%20and%20feature%20names%20are%20unnessesary%20changed%20to%20multilines%5Cr%5Cn%3Cimg%20width%3D%5C%221025%5C%22%20alt%3D%5C%22screen%20shot%202015-10-22%20at%2010%2022%2023%5C%22%20src%3D%5C%22https%3A//cloud.githubusercontent.com/assets/11270518/10661305/65b1cd04-78ad-11e5-8d61-f28b3d9ace16.png%5C%22%3E%5Cr%5Cnbefore%3A%5Cr%5Cn%3Cimg%20width%3D%5C%22894%5C%22%20alt%3D%5C%22screen%20shot%202015-10-22%20at%2010%2023%2002%5C%22%20src%3D%5C%22https%3A//cloud.githubusercontent.com/assets/11270518/10661311/786e98b4-78ad-11e5-95d6-7390f0ad47f0.png%5C%22%3E%5Cr%5Cn%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-10-22T09%3A19%3A04Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/11270518%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tommywo%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40tmullender%20%5Cr%5Cn1.%20merge%20commits%20into%20one%5Cr%5Cn2.%20change%20default%20entries%20per%20site%20to%20bigger%20number%20-%20I%20expect%2020%20is%20very%20small%20and%20I%20also%20would%20be%20happy%20if%20all%20items%20will%20be%20presented%2C%20without%20paging%20because%20only%20then%20I%20can%20quickly%20see%20which%20tests%20fail%22%2C%20%22created_at%22%3A%20%222015-10-22T18%3A34%3A15Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/9612911%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20think%20it%20would%20be%20nice%20if%20user%20could%20set%20default%20number%20of%20entries%20per%20site%20in%20jenkins.%22%2C%20%22created_at%22%3A%20%222015-10-23T07%3A55%3A26Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/11270518%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tommywo%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40damianszczepanik%20I%20believe%20I%20have%20combined%20the%20commits%20into%20one.%20%20There%20is%20now%20only%20one%20commit%20listed%20when%20I%20view%20the%20pull%20request%2C%20let%20me%20know%20if%20you%20see%20it%20differently.%20%20I%20can%20set%20the%20default%20page%20entries%20to%20All%20simply%20enough%20but%20configuration%20from%20jenkins%20is%20obviously%20a%20bit%20more%20work.%5Cr%5Cn%5Cr%5CnI%20had%20just%20applied%20the%20default%20styling%20from%20DataTables%2C%20I%20will%20take%20a%20look%20at%20the%20feature%20name%20wrapping%20and%20search%20field%20alignment%20but%20it%20might%20take%20me%20a%20few%20days%20to%20get%20to%20it.%22%2C%20%22created_at%22%3A%20%222015-10-23T09%3A16%3A55Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4955781%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tmullender%22%7D%7D%2C%20%7B%22body%22%3A%20%22The%20issue%20with%20the%20styling%20as%20I%20see%20it%20is%20the%20combination%20of%20dataTables%20adding%20padding%20for%20the%20sort%20images%20and%20960%20limiting%20the%20width%20of%20the%20table%20therefore%20forcing%20the%20first%20column%20to%20shrink%20and%20wrap.%20%5Cr%5Cn%5Cr%5CnShort%20term%20options%20I%20can%20see%3A%5Cr%5Cn1.%20reduce%20the%20padding%20slightly%20which%20reduces%20the%20wrapping%20a%20bit%20but%20not%20a%20load%5Cr%5Cn2.%20remove%20the%20sort%20images%20and%20just%20leave%20the%20ability%20to%20sort%20by%20clicking%20on%20the%20column%20header%5Cr%5Cn3.%20rework%20the%20layout%20to%20remove%20the%20960%20limitation%5Cr%5Cn%5Cr%5CnI%27m%20leaning%20towards%20option%202%20but%20what%20do%20you%20think%3F%20%5Cr%5Cn%5Cr%5CnA%20longer%20term%20option%20may%20be%20scrolling%20with%20%5Bfixed%20columns%5D%28https%3A//www.datatables.net/extensions/fixedcolumns/%29%22%2C%20%22created_at%22%3A%20%222015-10-23T17%3A21%3A09Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4955781%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/tmullender%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40tmullender%20if%20you%20apply%20second%20option%20than%20will%20we%20have%20graphical%20indicator%20that%20tells%20that%20column%20can%20be%20sorted%3F%20I%20think%20this%20is%20important%20if%20we%20want%20to%20keep%20UX%20better%21%5Cr%5Cn%5Cr%5Cn3rd%20sounds%20good%20to%20me%20but%20I%20expect%20that%20it%20may%20take%20a%20little%20bit.%20Also%20960%20is%20not%20a%20real%20limitation%20if%20you%20consider%20that%20results%20will%20be%20displayed%20on%20high%20resolution%20screens%20%28rather%20than%20on%20mobile%29%22%2C%20%22created_at%22%3A%20%222015-10-26T21%3A15%3A29Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/9612911%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/damianszczepanik%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/damianszczepanik/cucumber-reporting/pull/208#issuecomment-149910514'>General Comment</a></b>
- <a href='https://github.com/codecov-io'></a> ## [Current coverage][1] is `87.56%`
> Merging **#208** into **master** will not affect coverage as of [`5067e73`][3]
```diff
@@            master    #208   diff @@
======================================
Files           32      32
Stmts         1158    1158
Branches       164     164
Methods          0       0
======================================
Hit           1014    1014
Partial         45      45
Missed          99      99
```
> Review entire [Coverage Diff][4] as of [`5067e73`][3]
[1]: https://codecov.io/github/damianszczepanik/cucumber-reporting?ref=5067e736c2e0efb9c80eaacff517891032744d00
[2]: https://codecov.io/github/damianszczepanik/cucumber-reporting/features/suggestions?ref=5067e736c2e0efb9c80eaacff517891032744d00
[3]: https://codecov.io/github/damianszczepanik/cucumber-reporting/commit/5067e736c2e0efb9c80eaacff517891032744d00
[4]: https://codecov.io/github/damianszczepanik/cucumber-reporting/compare/4b1b8c6d1d1d56f77d4394c8270ac5345cbc8aee...5067e736c2e0efb9c80eaacff517891032744d00
> Powered by [Codecov](https://codecov.io). Updated on successful CI builds.
- <a href='https://github.com/damianszczepanik'></a> Looks good, but:
- can you merge all commits into one and then publish PR?
- I would like to see screenshot with new table, please attach
- <a href='https://github.com/tmullender'></a> stepstatistics
featurestatistics
I can't share the features I was testing with due to company policy so I've generated reports for cucumber-jvm's [java-helloworld](https://github.com/cucumber/cucumber-jvm/tree/master/examples/java-helloworld) example.  If you have a more complex example you want to see then let me know
- <a href='https://github.com/tommywo'></a> Nice feature!
What I don't like that search input is not aligned with table on tag overview and feature overview and feature names are unnessesary changed to multilines
screen shot 2015-10-22 at 10 22 23
before:
screen shot 2015-10-22 at 10 23 02
- <a href='https://github.com/damianszczepanik'></a> @tmullender
1. merge commits into one
2. change default entries per site to bigger number - I expect 20 is very small and I also would be happy if all items will be presented, without paging because only then I can quickly see which tests fail
- <a href='https://github.com/tommywo'></a> I think it would be nice if user could set default number of entries per site in jenkins.
- <a href='https://github.com/tmullender'></a> @damianszczepanik I believe I have combined the commits into one.  There is now only one commit listed when I view the pull request, let me know if you see it differently.  I can set the default page entries to All simply enough but configuration from jenkins is obviously a bit more work.
I had just applied the default styling from DataTables, I will take a look at the feature name wrapping and search field alignment but it might take me a few days to get to it.
- <a href='https://github.com/tmullender'></a> The issue with the styling as I see it is the combination of dataTables adding padding for the sort images and 960 limiting the width of the table therefore forcing the first column to shrink and wrap.
Short term options I can see:
1. reduce the padding slightly which reduces the wrapping a bit but not a load
2. remove the sort images and just leave the ability to sort by clicking on the column header
3. rework the layout to remove the 960 limitation
I'm leaning towards option 2 but what do you think?
A longer term option may be scrolling with [fixed columns](https://www.datatables.net/extensions/fixedcolumns/)
- <a href='https://github.com/damianszczepanik'></a> @tmullender if you apply second option than will we have graphical indicator that tells that column can be sorted? I think this is important if we want to keep UX better!
3rd sounds good to me but I expect that it may take a little bit. Also 960 is not a real limitation if you consider that results will be displayed on high resolution screens (rather than on mobile)

<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/208?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/damianszczepanik/cucumber-reporting/pull/208?approve=1'></a>&nbsp;<a href='https://github.com/damianszczepanik/cucumber-reporting/pull/208'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by damianszczepanik** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/damianszczepanik/cucumber-reporting/pull/208'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by damianszczepanik** [comment]
Looks good, but:
- can you merge all commits into one and then publish PR?
- I would like to see screenshot with new table, please attach

**Comment by tmullender** [comment]
stepstatistics

featurestatistics

I can't share the features I was testing with due to company policy so I've generated reports for cucumber-jvm's [java-helloworld](https://github.com/cucumber/cucumber-jvm/tree/master/examples/java-helloworld) example.  If you have a more complex example you want to see then let me know

**Comment by tommywo** [comment]
Nice feature! 
What I don't like that search input is not aligned with table on tag overview and feature overview and feature names are unnessesary changed to multilines
screen shot 2015-10-22 at 10 22 23
before:
screen shot 2015-10-22 at 10 23 02

**Comment by damianszczepanik** [comment]
@tmullender 
1. merge commits into one
2. change default entries per site to bigger number - I expect 20 is very small and I also would be happy if all items will be presented, without paging because only then I can quickly see which tests fail

**Comment by tommywo** [comment]
I think it would be nice if user could set default number of entries per site in jenkins.

**Comment by tmullender** [comment]
@damianszczepanik I believe I have combined the commits into one.  There is now only one commit listed when I view the pull request, let me know if you see it differently.  I can set the default page entries to All simply enough but configuration from jenkins is obviously a bit more work.

I had just applied the default styling from DataTables, I will take a look at the feature name wrapping and search field alignment but it might take me a few days to get to it.

**Comment by tmullender** [comment]
The issue with the styling as I see it is the combination of dataTables adding padding for the sort images and 960 limiting the width of the table therefore forcing the first column to shrink and wrap. 

Short term options I can see:
1. reduce the padding slightly which reduces the wrapping a bit but not a load
2. remove the sort images and just leave the ability to sort by clicking on the column header
3. rework the layout to remove the 960 limitation

I'm leaning towards option 2 but what do you think? 

A longer term option may be scrolling with [fixed columns](https://www.datatables.net/extensions/fixedcolumns/)

**Comment by damianszczepanik** [comment]
@tmullender if you apply second option than will we have graphical indicator that tells that column can be sorted? I think this is important if we want to keep UX better!

3rd sounds good to me but I expect that it may take a little bit. Also 960 is not a real limitation if you consider that results will be displayed on high resolution screens (rather than on mobile)

**Pull request closed without merging**
